
# MySQL Database Config
spring.datasource.url=jdbc:mysql://localhost:3306/pos_db
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# format SQL nicely
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2hhbmdlLXRoaXMtcmFuZG9tLXNlY3JldC1rZXktZm9yLXByb2QtaGVyZQ==



#email service
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nagarjuna.sanem@gmail.com
spring.mail.password=subidhgrbjxswbws
spring.mail.properties.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true